### ISSUE TITLE
What about dual sim android if I want to send message from selected sim...

### ISSUE THREAD

**Issue by sabik22** [babariviere/flutter_sms#12]
I want send sms from selected sim. any possiblity?

**Comment by piotrpalek** [comment]
Hey, I just want to add a little info in case others stumble upon this issue, I've been using this library just fine, but tried it on another phone and it didn't work, giving me this error:

```
E/flutter (15195): type 'PlatformException' is not a subtype of type 'String'
E/flutter (15195): #0      new SmsSender._private.<anonymous closure> (package:sms/sms.dart:311:71)
E/flutter (15195): #1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
E/flutter (15195): #2      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:352:15)
E/flutter (15195): #3      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:367:16)
E/flutter (15195): #4      _DelayedError.perform (dart:async/stream_impl.dart:589:14)
E/flutter (15195): #5      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694:11)
E/flutter (15195): #6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654:7)
E/flutter (15195): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (15195): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
(note: it appears for various errors not just this one)

My issue turned out to be that the phone had dual SIM support, but the phone didn't have a default SIM card for sending SMS selected (in the SIM Card settings).

**Comment by babariviere** [comment]
We are working on it but we don't have so much time

**Comment by piotrpalek** [comment]
No worries, I've just wanted to post it so others might have an easier time debugging this issue. Thanks for the work :+1:

**Comment by babariviere** [comment]
We have made an update in progress for dual sim support. Can someone test it? I don't have dual card sim and android emulator does not support multi card sim.
Here is the pull request #21.
