### ISSUE TITLE
Contact lookup appears to be failing (maybe just on M+?)

### ISSUE THREAD

**Issue by ArcticZeroo** [babariviere/flutter_sms#18]
I'm writing an app to perform analytics on SMS history, and I'm unable to load contacts on my device (which is on the P beta, but I don't think that should be relevant to the issue).

When I try to run thread.findContact() it pops up the permission dialog which lets me choose to allow the app to read my contacts. That works fine. However, then it immediately throws.

Here's the stacktrace produced by the java method channel hook:
```
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): Failed to handle method call
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): java.lang.NegativeArraySizeException: -1
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): 	at com.babariviere.sms.ContactPhotoQueryHandler.queryContactPhoto(ContactPhotoQuery.java:78)
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): 	at com.babariviere.sms.ContactPhotoQueryHandler.handle(ContactPhotoQuery.java:46)
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): 	at com.babariviere.sms.ContactPhotoQuery.onMethodCall(ContactPhotoQuery.java:133)
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:136)
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): 	at android.app.ActivityThread.main(ActivityThread.java:6642)
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.babariviere.com/queryContactPhoto(25064): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Which can be found here https://github.com/babariviere/flutter_sms/blob/master/android/src/main/java/com/babariviere/sms/ContactPhotoQuery.java#L78

I would try to help fix it but unfortunately I am not very experienced with the Android side of Java.

Is this perhaps my issue?  If you'd like, you can see how I'm setting up the threads here: https://github.com/ArcticZeroo/sms_analytics/blob/master/lib/api/sms_manager.dart#L78

**Comment by babariviere** [comment]
Oh yes, good catch. I will fix this tonight

**Comment by babariviere** [comment]
If you want to fix it, you can check this link to understand the bug: https://stackoverflow.com/questions/44875399/android-java-lang-negativearraysizeexception-1

**Comment by babariviere** [comment]
I've uploaded a new version, can you tell me if this works now?
