### ISSUE TITLE
Error when trying to send message with no money on account

### ISSUE THREAD

**Issue by piotrpalek** [babariviere/flutter_sms#20]
Hey, I've been testing out this package with a pre-paid card and at some point the money ran out on it. I didn't know it at the time, I just started getting this error:

```
E/flutter ( 2677): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 2677): type 'PlatformException' is not a subtype of type 'String'
E/flutter ( 2677): #0      new SmsSender._private.<anonymous closure> (package:sms/sms.dart:311:71)
E/flutter ( 2677): #1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
E/flutter ( 2677): #2      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:352:15)
E/flutter ( 2677): #3      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:367:16)
E/flutter ( 2677): #4      _DelayedError.perform (dart:async/stream_impl.dart:589:14)
E/flutter ( 2677): #5      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694:11)
E/flutter ( 2677): #6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654:7)
E/flutter ( 2677): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 2677): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

Now that I know that, is there some way to catch this error so I can handle it? For eg. so that I can show a message with an error or keep the message in the queue to retry sending later.

**Comment by babariviere** [comment]
You can use a try-catch clause.

Here is some doc [](https://www.dartlang.org/guides/language/language-tour#catch)

And here is an example:

```dart
try {
  sendMessage(..);
} catch (e) {
  print("No more money");
  queue.add(msg);
}
```

**Comment by babariviere** [comment]
I may improve error handling in the future. So I will post a new comment when I have done something for this function.

**Comment by ridho9** [comment]
I also get the same error message, but my sim card does have balance in it.

**Comment by babariviere** [comment]
This error should be fixed by now
