### ISSUE TITLE
Send SMS Permisson Error

### ISSUE THREAD

**Issue by claudesoft** [babariviere/flutter_sms#22]
Hi, when i try to send an SMS i get this error:

AndroidRuntime(10682): Process: com.example.smsapp, PID: 10682
E/AndroidRuntime(10682): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=2, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.example.smsapp/com.example.smsapp.MainActivity}: java.lang.SecurityException: Neither user 10279 nor current process has android.permission.READ_PHONE_STATE.

So for android 8 / Huawei Mate 9 i need to ask READ_PHONE_STATE over platform channels and then it works, but it would be better if the Plugin ask this Permission for me.

Thx

**Comment by babariviere** [comment]
Hi, have you accepted all permissions from the pop-up?

**Comment by claudesoft** [comment]
Yes

**Comment by babariviere** [comment]
Can you show me the full log please?

**Comment by babariviere** [comment]
And if possible the piece of code where you send the sms?

**Comment by claudesoft** [comment]
```
Launching lib/main.dart on MHA L09 in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
I/FlutterActivityDelegate(16906): onResume setting current activity to this
D/OpenGLRenderer(16906):   HWUI Binary is  enabled
W/InputMethodManager(16906): startInputReason = 1
W/InputMethodManager(16906): startInputReason = 5
I/hwaps   (16906): JNI_OnLoad
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): Failed to handle method call
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): java.lang.SecurityException: Neither user 10279 nor current process has android.permission.READ_PHONE_STATE.
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at android.os.Parcel.readException(Parcel.java:1945)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at android.os.Parcel.readException(Parcel.java:1891)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at com.android.internal.telephony.ISms$Stub$Proxy.sendTextForSubscriber(ISms.java:881)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at android.telephony.SmsManager.sendTextMessageInternal(SmsManager.java:338)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at android.telephony.SmsManager.sendTextMessage(SmsManager.java:317)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at com.babariviere.sms.SmsSenderMethodHandler.sendSmsMessage(SmsSender.java:96)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at com.babariviere.sms.SmsSenderMethodHandler.handle(SmsSender.java:51)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at com.babariviere.sms.SmsSender.onMethodCall(SmsSender.java:124)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:152)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at android.os.Looper.loop(Looper.java:144)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at android.app.ActivityThread.main(ActivityThread.java:7406)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/MethodChannel#plugins.babariviere.com/sendSMS(16906): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
V/AudioManager(16906): playSoundEffect   effectType: 0

```

I think its a Bug in Android 8 :/ 

[https://stackoverflow.com/questions/46421412/android-8-requires-read-phone-state-when-calling-smsmanager-sendtextmessage](https://stackoverflow.com/questions/46421412/android-8-requires-read-phone-state-when-calling-smsmanager-sendtextmessage)

**Comment by babariviere** [comment]
Yes it's a bug with Android O. I have pushed a fix, can you test it? The version is 0.1.6 now

**Comment by claudesoft** [comment]
It works THX!!! :)

**Comment by babariviere** [comment]
Cool :smile:

**Comment by claudesoft** [comment]
Do you have a BTC or ETH Address  to send you a little thanks?

**Comment by babariviere** [comment]
No sorry, but thanks that's really kind !
